create sequence s_id_user
start with 1 increment by 1
MINVALUE 1 MAXVALUE 100000
CYCLE CACHE 2 ORDER;

create sequence s_id_user_firm
start with 1 increment by 1
MINVALUE 1 MAXVALUE 100000
CYCLE CACHE 2 ORDER;

create sequence s_id_client
start with 1 increment by 1
MINVALUE 1 MAXVALUE 100000
CYCLE CACHE 2 ORDER;

create sequence s_id_facture
start with 1 increment by 1
MINVALUE 1 MAXVALUE 100000
CYCLE CACHE 2 ORDER;

create sequence s_id_position
start with 1 increment by 1
MINVALUE 1 MAXVALUE 100000
CYCLE CACHE 2 ORDER;

create sequence s_id_contact
start with 1 increment by 1
MINVALUE 1 MAXVALUE 100000
CYCLE CACHE 2 ORDER;

create sequence s_id_address
start with 1 increment by 1
MINVALUE 1 MAXVALUE 100000
CYCLE CACHE 2 ORDER;

create sequence s_id_worker
start with 1 increment by 1
MINVALUE 1 MAXVALUE 100000
CYCLE CACHE 2 ORDER;

create sequence s_id_contract_type
start with 1 increment by 1
MINVALUE 1 MAXVALUE 100000
CYCLE CACHE 2 ORDER;

create sequence s_id_contract
start with 1 increment by 1
MINVALUE 1 MAXVALUE 100000
CYCLE CACHE 2 ORDER;

create sequence s_id_product_type
start with 1 increment by 1
MINVALUE 1 MAXVALUE 100000
CYCLE CACHE 2 ORDER;

create sequence s_id_warehouse
start with 1 increment by 1
MINVALUE 1 MAXVALUE 100000
CYCLE CACHE 2 ORDER;

create sequence s_id_product
start with 1 increment by 1
MINVALUE 1 MAXVALUE 100000
CYCLE CACHE 2 ORDER;

create sequence s_id_order_status
start with 1 increment by 1
MINVALUE 1 MAXVALUE 100000
CYCLE CACHE 2 ORDER;

create sequence s_id_order_user
start with 1 increment by 1
MINVALUE 1 MAXVALUE 100000
CYCLE CACHE 2 ORDER;

create sequence s_id_address_type
start with 1 increment by 1
MINVALUE 1 MAXVALUE 100000
CYCLE CACHE 2 ORDER;

create sequence s_id_client_firm
start with 1 increment by 1
MINVALUE 1 MAXVALUE 100000
CYCLE CACHE 2 ORDER;

--=========================================CREATE TABLE
CREATE TABLE USERS
(
  ID_USER INTEGER CONSTRAINT id_user_pk PRIMARY KEY
, PASS VARCHAR2(60) 
, EMAIL VARCHAR2(50) 
, STATUS NUMBER(1,0) DEFAULT 1
, INSERT_DATE TIMESTAMP default sysdate
);

CREATE TABLE USERS_FIRM
(
  ID_USER_FIRM   INTEGER CONSTRAINT id_user_firm_pk PRIMARY KEY
, FNAME VARCHAR2(30) 
, LNAME VARCHAR2(30) 
, FIRM_NAME VARCHAR2(100) 
, NIP VARCHAR2(30) 
, CITY VARCHAR2(30) 
, ADDRESS VARCHAR2(30) 
, POST_CODE VARCHAR2(10) 
, STATUS NUMBER(1,0) DEFAULT 1
, ID_USER INTEGER
, INSERT_DATE TIMESTAMP default sysdate 
, CONSTRAINT id_user_fk FOREIGN KEY (ID_USER) REFERENCES USERS(ID_USER)
);

CREATE TABLE PRODUCT_TYPE
(
  ID_PRODUCT_TYPE INTEGER CONSTRAINT id_product_type_pk PRIMARY KEY
, PRODUCT_TYPE VARCHAR2(30) 
, DESCRIPTION VARCHAR(100)
, ID_USER INTEGER
, STATUS NUMBER(1,0) DEFAULT 1
, INSERT_DATE TIMESTAMP default sysdate 
);

CREATE TABLE PRODUCT 
(
  ID_PRODUCT   INTEGER CONSTRAINT id_product_pk PRIMARY KEY
, PRODUCT_NAME VARCHAR2(30) 
, DESCRIPTION VARCHAR2(100) 
, ID_PRODUCT_TYPE INTEGER
, ID_USER INTEGER
, STATUS NUMBER(1,0) DEFAULT 1
, INSERT_DATE TIMESTAMP default sysdate 
, CONSTRAINT id_user_product_fk FOREIGN KEY (ID_USER) REFERENCES USERS(ID_USER)
, CONSTRAINT id_product_type_fk FOREIGN KEY (ID_PRODUCT_TYPE) REFERENCES PRODUCT_TYPE(ID_PRODUCT_TYPE)
);

CREATE TABLE CLIENT
(
  ID_CLIENT   INTEGER CONSTRAINT id_client_pk PRIMARY KEY
, FNAME VARCHAR2(30) 
, LNAME VARCHAR2(30) 
, PESEL NUMBER(11)
, DATE_ADD varchar(10) 
, ID_USER INTEGER
, STATUS NUMBER(1,0) DEFAULT 1
, INSERT_DATE TIMESTAMP default sysdate 
, CONSTRAINT id_user_client_fk FOREIGN KEY (ID_USER) REFERENCES USERS(ID_USER)
);

CREATE TABLE FACTURE
(
  ID_FACTURE   INTEGER CONSTRAINT id_facture_pk PRIMARY KEY
, FACTURE_NAME VARCHAR2(30) 
, ID_CLIENT INTEGER
, DATE_ADD VARCHAR2(10)
, VALUE VARCHAR2(10)
, ID_USER INTEGER
, STATUS NUMBER(1,0) DEFAULT 1
, INSERT_DATE TIMESTAMP default sysdate 
, CONSTRAINT id_user_facture_fk FOREIGN KEY (ID_USER) REFERENCES USERS(ID_USER)
, CONSTRAINT id_client_facture_fk FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT)
);

CREATE TABLE POSITION
(
  ID_POSITION   INTEGER CONSTRAINT id_position_pk PRIMARY KEY
, ID_FACTURE INTEGER
, ID_PRODUCT INTEGER
, AMOUNT VARCHAR2(15)
, VALUE_COST VARCHAR2(10)
, STATUS NUMBER(1,0) DEFAULT 1
, INSERT_DATE TIMESTAMP default sysdate 
, CONSTRAINT id_position_facture_fk FOREIGN KEY (ID_FACTURE) REFERENCES FACTURE(ID_FACTURE)
, CONSTRAINT id_position_product_fk FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT)
);

CREATE TABLE WORKER
(
  ID_WORKER   INTEGER CONSTRAINT id_worker_pk PRIMARY KEY
, FNAME VARCHAR2(30) 
, LNAME VARCHAR2(30) 
, PESEL VARCHAR2(11) 
, DATE_ADD varchar(10) 
, ID_USER INTEGER
, STATUS NUMBER(1,0) DEFAULT 1
, INSERT_DATE TIMESTAMP default sysdate 
, CONSTRAINT id_user_worker_fk FOREIGN KEY (ID_USER) REFERENCES USERS(ID_USER)
);

CREATE TABLE CONTRACT_TYPE
(
  ID_CONTRACT_TYPE   INTEGER CONSTRAINT id_contract_type_pk PRIMARY KEY
, CONTRACT_NAME VARCHAR2(50) 
, STATUS NUMBER(1,0) DEFAULT 1
, INSERT_DATE TIMESTAMP default sysdate 
);

CREATE TABLE CONTRACT
(
  ID_CONTRACT   INTEGER CONSTRAINT id_contract_pk PRIMARY KEY
, ID_WORKER INTEGER
, ID_CONTRACT_TYPE INTEGER
, START_DATE varchar(10) 
, END_DATE varchar(10) default '12/12/2100'
, SALARY varchar(10)
, STATUS NUMBER(1,0) DEFAULT 1
, INSERT_DATE TIMESTAMP default sysdate 
, CONSTRAINT id_contract_type_fk FOREIGN KEY (ID_CONTRACT_TYPE) REFERENCES CONTRACT_TYPE(ID_CONTRACT_TYPE)
, CONSTRAINT id_contract_worker_fk FOREIGN KEY (ID_WORKER) REFERENCES WORKER(ID_WORKER)
);

CREATE TABLE ORDER_STATUS
(
  ID_ORDER_STATUS INTEGER CONSTRAINT id_order_status_pk PRIMARY KEY
, ORDER_STATUS_NAME VARCHAR2(11) 
, STATUS NUMBER(1,0) DEFAULT 1
, INSERT_DATE TIMESTAMP default sysdate 
);

CREATE TABLE ORDER_USER
(
  ID_ORDER INTEGER CONSTRAINT id_order_pk PRIMARY KEY
, ORDER_NUMBER VARCHAR2(8) 
, ID_CLIENT NUMBER
, ID_PRODUCT NUMBER
, AMOUNT_PRODUCT VARCHAR2(30) 
, ORDER_DATE VARCHAR2(10) 
, ID_ORDER_STATUS INTEGER
, ID_USER INTEGER
, STATUS NUMBER(1,0) DEFAULT 1
, INSERT_DATE TIMESTAMP default sysdate 
, CONSTRAINT id_user_order_fk FOREIGN KEY (ID_USER) REFERENCES USERS(ID_USER)
, CONSTRAINT id_status_order_fk FOREIGN KEY (ID_ORDER_STATUS) REFERENCES ORDER_STATUS(ID_ORDER_STATUS)
);

CREATE TABLE WAREHOUSE
(
  ID_WAREHOUSE   INTEGER CONSTRAINT id_warehouse_pk PRIMARY KEY
, ID_PRODUCT NUMBER 
, PRODUCT_AMOUNT INTEGER
, DATE_ADD varchar(10) 
, STATUS NUMBER(1,0) DEFAULT 1
, INSERT_DATE TIMESTAMP default sysdate 
, CONSTRAINT id_product_n_fk FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT)
);

CREATE TABLE CONTACT 
(
  ID_CONTACT   INTEGER CONSTRAINT id_contact_pk PRIMARY KEY
, email VARCHAR2(40) 
, tel_1 NUMBER(12) 
, tel_2 NUMBER(12)
, ID_WORKER INTEGER default null 
, ID_CLIENT INTEGER default null 
, STATUS NUMBER(1,0) DEFAULT 1
, INSERT_DATE TIMESTAMP default sysdate 
, CONSTRAINT id_contact_client_fk FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT)
, CONSTRAINT id_contact_worker_fk FOREIGN KEY (ID_WORKER) REFERENCES WORKER(ID_WORKER)
);

CREATE TABLE ADDRESS_TYPE
(
  ID_ADDRESS_TYPE   INTEGER CONSTRAINT id_address_type_pk PRIMARY KEY
, ADDRESS_TYPE VARCHAR2(20) 
, STATUS NUMBER(1,0) DEFAULT 1
, INSERT_DATE TIMESTAMP default sysdate 
);

CREATE TABLE ADDRESS
(
  ID_ADDRESS   INTEGER CONSTRAINT id_address_pk PRIMARY KEY
, CITY VARCHAR2(30) 
, STREET VARCHAR2(40)
, PCODE VARCHAR2(6)
, HNUMBER VARCHAR2(5)
, ID_ADDRESS_TYPE INTEGER 
, ID_WORKER INTEGER default null 
, ID_CLIENT INTEGER default null 
, STATUS NUMBER(1,0) DEFAULT 1
, INSERT_DATE TIMESTAMP default sysdate 
, CONSTRAINT id_address_client_fk FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT)
, CONSTRAINT id_address_worker_fk FOREIGN KEY (ID_WORKER) REFERENCES WORKER(ID_WORKER)
, CONSTRAINT id_address_type_addres_fk FOREIGN KEY (ID_ADDRESS_TYPE) REFERENCES ADDRESS_TYPE(ID_ADDRESS_TYPE)
);

CREATE TABLE CLIENT_FIRM
(
  ID_CLIENT_FIRM   INTEGER CONSTRAINT id_client_firm_pk PRIMARY KEY
, FIRM_NAME VARCHAR2(50) 
, NIP NUMBER(10)
, REGON VARCHAR2(15)
, ADDRESS VARCHAR2(100)
, ID_CLIENT INTEGER 
, STATUS NUMBER(1,0) DEFAULT 1
, INSERT_DATE TIMESTAMP default sysdate 
, CONSTRAINT id_client_firm_fk FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT)
);